import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {SidebarProvider, SidebarTrigger, SidebarRail} from "@/components/ui/sidebar";
import {AppSidebar} from "@/components/app-sidebar";
import {ThemeProvider} from "@/app/theme-provider";
import { cookies } from "next/headers"
import {Separator} from "@/components/ui/separator";
import {cn} from "@/lib/utils";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const cookieStore = await cookies()
    const defaultOpen = cookieStore.get("sidebar:state")?.value === "true"
    return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider attribute="class"
                     defaultTheme="dark"
                     enableSystem
                     disableTransitionOnChange
      >
      <SidebarProvider defaultOpen={defaultOpen}>
          <AppSidebar />
          {/*<SidebarTrigger />*/}
          <main className="w-full">
              {children}
          </main>
      </SidebarProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
